name: CI

on:
  merge_group:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  commitlint:
    name: Commit
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        name: Install pnpm
        with:
          version: 9.14.2
      - name: Install with pnpm
        run: pnpm install --frozen-lockfile
      - name: Check commit message
        uses: wagoid/commitlint-github-action@3d28780bbf0365e29b144e272b2121204d5be5f3 # v6.1.2
        with:
          configFile: commitlint.config.cjs
          failOnWarnings: false
          helpURL: https://github.com/ducktors/turborepo-remote-cache#how-to-commit

  install:
    runs-on: ${{ matrix.os }}
    name: Install
    strategy:
      matrix:
        node-version: [20.x, 22.x]
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        name: Checkout
      - name: Use Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install with npm
        run: |
          cd ${{ github.workspace }}
          mkdir npm-repro
          cd npm-repro
          npm init -y
          npm install turborepo-remote-cache
      - name: Install with yarn
        run: |
          cd ${{ github.workspace }}
          mkdir yarn-repro
          cd yarn-repro
          npm init -y
          yarn add turborepo-remote-cache

  build:
    runs-on: ${{ matrix.os }}
    name: Build
    strategy:
      matrix:
        node-version: [20.x, 22.x]
        os: [ubuntu-latest]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        name: Checkout
      - name: Use Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        name: Install pnpm
        with:
          version: 9.14.2
      - name: Install with pnpm
        run: pnpm install
      - name: Lint code
        run: pnpm lint
      - name: Build
        run: pnpm build
