name: CI

on:
  merge_group:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commitlint:
    name: Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check commit message
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js
          failOnWarnings: false
          helpURL: https://github.com/ducktors/turborepo-remote-cache#how-to-commit

  install:
    runs-on: ${{ matrix.os }}
    name: Install
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install with npm
        run: |
          cd ${{ github.workspace }}
          mkdir npm-repro
          cd npm-repro
          npm init -y
          npm install turborepo-remote-cache
      - name: Install with yarn
        run: |
          cd ${{ github.workspace }}
          mkdir yarn-repro
          cd yarn-repro
          npm init -y
          yarn add turborepo-remote-cache

  build:
    runs-on: ${{ matrix.os }}
    name: Build
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
      - name: Install with pnpm
        run: pnpm install
      - name: Lint code
        run: pnpm lint
      - name: Build
        run: pnpm build

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
      - name: Install with pnpm
        run: pnpm install
      - name: Run tests
        run: pnpm test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: CodeClimate
        continue-on-error: true
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
        with:
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
          
  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ducktors/turborepo-remote-cache
          flavor: latest=true
          tags: type=raw
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/x86_64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: |
            ducktors/turborepo-remote-cache:latest
