name: Fly.io Preview
on:
  pull_request:
    types: [opened, synchronize]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP: turborepo-remote-cache
  FLY_URL: https://turborepo-remote-cache.fly.dev/v8/artifacts/status

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github repo
        uses: actions/checkout@v4

      - name: Deploy app
        uses: superfly/flyctl-actions@1.3
        with:
          args:
            'deploy --app ${{ env.FLY_APP }} -c fly.toml'

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ env.FLY_URL }}
          max-attempts: 3
          retry-delay: 15s

      - name: Post link to PR Preview
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Your PR is deployed, see it [here](${{ env.FLY_URL }})
          mode: recreate
